GET http://localhost:8080/api/vehicle

###

GET http://localhost:8080/vehicle

###

GET http://localhost:8080/vehicle/23
Accept: application/json

### custom json

GET http://localhost:8080/vehicle/myjson
Accept: application/json

### custom response

GET http://localhost:8080/vehicle/myresponse?no=2
Accept: application/json
